name: DBD Sanity Test

on:
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the repository
      uses: actions/checkout@v3
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Append MSMS path to PATH environment variables
      run: |
        echo "$GITHUB_WORKSPACE/msms" >> $PATH
        echo $GITHUB_PATH
        echo $PATH
        msms
    - name: Run the sanity test executables
      run: python run.py
